
version: 2
updates:
  - package-ecosystem: "pip"   # Para Python/Poetry, use "pip" aqui
    directory: "/"             # Ajuste se seus arquivos estiverem em subpasta
    schedule:
      interval: "daily"        # Daily só para acelerar o próximo job (depois volte para weekly)
    open-pull-requests-limit: 5
``


